[package]
name = "lambdaworks-circom-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks-math.workspace = true
lambdaworks-groth16.workspace = true

serde = { version = "1.0" }
serde_json = "1"
