[package]
name = "arkworks_adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks-math.workspace = true
lambdaworks-groth16.workspace = true
ark-r1cs-std = { version = "^0.3.1" }
ark-bls12-381 = { version = "0.4.0" }
ark-ff = { version = "^0.4.2" }
ark-relations = { version = "^0.4.0" }
ark-serialize = { version = "0.4.2" }
num-bigint = { version = "0.4", default-features = false }
rand = "0.8.5"
