name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.90.0
      - name: Publish crate lambdaworks-gpu
        run: cargo publish -p lambdaworks-gpu --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish crate lambdaworks-math
        run: cargo publish -p lambdaworks-math --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --features "parallel std alloc lambdaworks-serde-binary lambdaworks-serde-string proptest instruments"
      - name: Publish crate lambdaworks-crypto
        run: cargo publish -p lambdaworks-crypto --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --features "asm std serde test_fiat_shamir parallel alloc"
