name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.87.0
      - name: Publish crate cairo-vm
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --all-features
